### ISSUE TITLE
Upload source code to maven repository in addition to the javadocs

### ISSUE THREAD

**Issue by jheadley** [logintc/logintc-java#4]
In ```pom.xml``` at line 105 just after ```</plugin>```, if you add the xml below:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                    <id>attach-sources</id>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                    </execution>
                </executions>
            </plugin>
```

Then the source code will be uploaded to the maven repository along with the javadoc during ```mvn install```.

This will allow the developer's IDE to download the source so that the developer can easily navigate to the source code for the java client.

**Comment by dmatute** [comment]
Thank you for the suggestion. There is no current plan to upload the source and/or javadocs to the maven repository.
